TTNNWeb/Controllers/DanhSachThiSinhController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrungTamNgoaiNgu.BUS;
using TrungTamNgoaiNgu.DTO;

namespace TTNNWeb.Controllers
{
    public class DanhSachThiSinhController : Controller
    {
        Bus_DSPhongThi bus_dsPhongThi = new Bus_DSPhongThi();

        public ActionResult Index()
        {
            var dsKhoaThi = bus_dsPhongThi.LayDanhSachKhoaThi();
            ViewBag.dsKhoaThi = new SelectList(dsKhoaThi, "Id", "TenKhoaThi");
            ViewBag.dsPhongThi = new SelectList(bus_dsPhongThi.LayDanhSachPhongThi(dsKhoaThi[0].Id), "Id", "TenPhongThi"); ;
            return View();
        }
        public ActionResult LayDanhSachPhongThi(int? khoaThiId)
        {

            List<Dto_PhongThi> dsPhongThi = bus_dsPhongThi.LayDanhSachPhongThi((int)khoaThiId);

            return Json(dsPhongThi, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LayDanhSachThiSinh(int? khoaThiId, int? phongThiId)
        {
            List<Dto_DSPhongThi> dsThiSinhTheoPhong = bus_dsPhongThi.DanhSachThiSinhTheoKhoaVaPhong((int)khoaThiId, (int)phongThiId);

            return Json(dsThiSinhTheoPhong, JsonRequestBehavior.AllowGet);
        }

        public ActionResult HienBangDanhSach(int? khoaThiId, int? phongThiId)
        {
            List<Dto_DSPhongThi> dsThiSinhTheoPhong = bus_dsPhongThi.DanhSachThiSinhTheoKhoaVaPhong((int)khoaThiId, (int)phongThiId);

            return PartialView(dsThiSinhTheoPhong);
        }
    }
}

TTNNWeb/Views/DanhSachThiSinh/Index.cshtml
@model TTNNWeb.Models.DanhSachThi

@{
    ViewBag.Title = "Index";
}

<h2>Danh sách thí sinh dự thi</h2>

<script type="text/javascript">
    $(document).ready(function () {
        location.reload();
    });

    function layDanhSachPhongThi() {
        

        var kid = $('#Id_KhoaThi').val();
        $("#Id_PhongThi").html("");

        $.ajax({
            cache: false,
            url: '@Url.Action("LayDanhSachPhongThi", "DanhSachThiSinh")',
            type: "GET",
            dataType: "JSON",
            data: { khoaThiId: kid},
            success: function (response) {
                $("table tbody").empty();
                    
                    $.each(response, function (index, value) {
                        $("#Id_PhongThi").append(
                            $('<option></option>').val(value.Id).html(value.TenPhongThi));
                    });
                    $('#Id_PhongThi').val(1);
                    layDanhSachThiSinh();
            },
            error: function (response) {
                $("table tbody").empty();
            }
        });
    }

    function layDanhSachThiSinh() {

        var kid = $('#Id_KhoaThi').val();
        var pid = $('#Id_PhongThi').val();

        $.ajax({
            cache: false,
            url: '@Url.Action("LayDanhSachThiSinh", "DanhSachThiSinh")',
            type: "GET",
            dataType: "JSON",
            data: { khoaThiId: kid, phongThiId: pid },
            success: function (response) {
                $("table tbody").empty();
                var row = "";
                $.each(response, function (index, value) {

                    row += "<tr>"
                        + "<td>" + value.SoThuTu + "</td>"
                        + "<td>" + value.SBD + "</td>"
                        + "<td>" + value.TenThiSinh + "</td>"
                        + "<td>" + '<a href="/ThiSinh/Detail/' + value.Id_ThiSinh + '">Thông tin thí sinh<a/>' + " | "
                        + '<a href="/ThiSinh/Result?phongThiId=' + value.Id_PhongThi + "&thiSinhId=" + value.Id_ThiSinh + '">Kết quả thi</a>' + " | "
                        + '<a href="/ThiSinh/Certificate?phongThiId=' + value.Id_PhongThi + "&thiSinhId=" + value.Id_ThiSinh + '">Giấy chứng nhận</a>' + "</td>"
                        + "</tr>";
                });
                $("table tbody").append(row);
            },
            error: function (response) {
                console.log("error");
            }
        });
    }


</script>

<div>
    <p>
        Chọn khóa thi:
        @Html.DropDownListFor(model => model.Id_KhoaThi, ViewBag.dsKhoaThi as SelectList, new { @class = "form-control", @onChange = "layDanhSachPhongThi()" })
    </p>
    <p>
        Chọn phòng thi:
        @Html.DropDownListFor(model => model.Id_PhongThi, ViewBag.dsPhongThi as SelectList, htmlAttributes: new { @class = "form-control", @onClick = "layDanhSachThiSinh()" })
    </p>
</div>

<div style="margin: 20px 0">
    <h4 class="title">Chi tiết danh sách</h4>
</div>

<div  style="min-height: 40vh">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Số thứ tự
                </th>
                <th>
                    Số báo danh
                </th>
                <th>
                    Tên thí sinh
                </th>
                <th>
                    Hành động
                </th>
            </tr>

        </thead>
        <tbody></tbody>

    </table>

</div>