TTNNWeb/Controllers/DangKyThiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Dynamic;
using TrungTamNgoaiNgu.BUS;
using System.Text.RegularExpressions;

namespace TTNNWeb.Controllers
{
    
    public class DangKyThiController : Controller
    {
        // GET: DangKyThi
        Bus_ThiSinh busThisinh = new Bus_ThiSinh();
        Bus_KhoaThi buskhoathi = new Bus_KhoaThi();
        Bus_PhieuDangKy busPdk = new Bus_PhieuDangKy();
        DateTime now = DateTime.Now;
        int idTS;

         public static bool IsPhoneNumber(string number)
        {
            return Regex.Match(number, @"^([0-9]{10})$").Success;
        }

        public static bool IsIdCard(string number)
        {
            return Regex.Match(number, @"^([0-9]{9,12})$").Success;
        }
        public ActionResult Index()
        {
            ViewBag.ListKhoaThi = new SelectList(buskhoathi.LayDanhSachKhoaThiChuaLapDanhSach(), "Id", "TenKhoaThi");
            return View();
        }

        [HttpPost]
        public ActionResult Index( TrungTamNgoaiNgu.DTO.Dto_ThiSinh_PhieuDangKy thisinh)
        {
            ViewBag.ListKhoaThi = new SelectList(buskhoathi.LayDanhSachKhoaThiChuaLapDanhSach(), "Id", "TenKhoaThi");
            if ((string.IsNullOrEmpty(thisinh.HoTen)) || string.IsNullOrEmpty(thisinh.NoiSinh) || string.IsNullOrEmpty(thisinh.CMND) || string.IsNullOrEmpty(thisinh.NoiCap) || string.IsNullOrEmpty(thisinh.GioiTinh) || string.IsNullOrEmpty(thisinh.SDT))
            {
                ViewBag.Error = "Vui lòng điền đầy đủ thông tin";
                return View(thisinh);
            }
            else if (!IsPhoneNumber(thisinh.SDT))
            {
                ViewBag.Error = "Số điện thoại là dãy có 10 chữ số";
                return View(thisinh);
            }
            else if (!IsIdCard(thisinh.CMND))
            {
                ViewBag.Error = "CMND/CCCD là dãy số có 9-12 số";
                return View(thisinh);
            }
            else
            {
                if (busThisinh.ThemTS(thisinh))
                {
                   thisinh.NgayDangKy = now;
                   busPdk.DKDuThi(thisinh);
                }
                return View("DangKyThanhCong");
            }
        }

    }
}

TTNNWeb/Controllers/GiayChungNhanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrungTamNgoaiNgu.BUS;

namespace TTNNWeb.Controllers
{
    public class GiayChungNhanController : Controller
    {
        Bus_DSPhongThi bus_DSPhongThi = new Bus_DSPhongThi();
        public ActionResult Index(int? khoaThiId, string sbd)
        {
            ViewBag.dsKhoaThi = bus_DSPhongThi.LayDanhSachKhoaThi();

            if (khoaThiId  > -1 && !string.IsNullOrEmpty(sbd))
            {
                if (bus_DSPhongThi.TonTaiSBD((int)khoaThiId, sbd))
                {
                    var ketqua = bus_DSPhongThi.LayGiayChungNhan((int)khoaThiId, sbd);
                    ViewBag.thoiGian = "TP.HCM, ngày " + DateTime.Now.Day.ToString() + " tháng " + DateTime.Now.Month.ToString() + " năm " + DateTime.Now.Year.ToString();
                    return View("../ThiSinh/Certificate", ketqua);
                }
                else
                    ViewBag.Error = "Không tìm thấy thông tin thí sinh";
               
            }    
            if(Request.Url.AbsoluteUri.ToString().ToLower().Contains("sbd") && string.IsNullOrEmpty(sbd))
                ViewBag.Error = "Vui lòng nhập số báo danh của thí sinh";
            return View();
        }
    }
}

TTNNWeb/Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrungTamNgoaiNgu.BUS;

namespace TTNNWeb.Controllers
{
    public class ThongKeController : Controller
    {
        Bus_ThongKe bus_ThongKe = new Bus_ThongKe();
        public ActionResult Index(string trinhDo)
        {
            if (!string.IsNullOrEmpty(trinhDo))
            {
                var thongke = bus_ThongKe.LayDanhSachThongKe(trinhDo);
                ViewBag.trinhDo = "Kết quả thống kê theo trình độ ''" + trinhDo + "''";
                return View(thongke);
            }
            return View();
        }
    }
}

TTNNWeb/Controllers/TraCuuController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TrungTamNgoaiNgu.BUS;
using TrungTamNgoaiNgu.DTO;

namespace TTNNWeb.Controllers
{
    public class TraCuuController : Controller
    {
        Bus_DSPhongThi bus = new Bus_DSPhongThi();

        public ActionResult Index(string boLoc, string tuKhoa)
        {

            if (!string.IsNullOrEmpty(boLoc) && !string.IsNullOrEmpty(tuKhoa))
            {
                var dsKetQua = bus.TimKiemThiSinh(boLoc, tuKhoa);
                if (dsKetQua != null)
                {
                    ViewBag.timKiem = "Kết quả tìm kiếm cho ''" + tuKhoa + "''";
                    return View(dsKetQua);
                }
                else
                    ViewBag.Error = "Không tìm thấy thí sinh dự thi.";
            }
            if (!string.IsNullOrEmpty(boLoc) && string.IsNullOrEmpty(tuKhoa))
                ViewBag.Error = "Vui lòng nhập từ khóa cần tìm kiếm.";
            return View();

        }


    }
       
}

TTNNWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Trung tâm ngoại ngữ", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Đăng ký thi", "Index", "DangKyThi")</li>
                    <li>@Html.ActionLink("Tra cứu kết quả", "Index", "TraCuu")</li>
                    <li>@Html.ActionLink("Giấy chứng nhận", "Index", "GiayChungNhan")</li>
                    <li>@Html.ActionLink("Danh sách dự thi", "Index", "DanhSachThiSinh")</li>
                    <li>@Html.ActionLink("Thống kê", "Index", "ThongKe")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>